title = "VEX PROS Coding Style"
baseurl = "http://github.org/StandsForSomething/pros-coding-style"
languageCode = "en-us"
theme = "docuapi"
canonifyURLs = true

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
wpygmentsUseClasses = true